FROM mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04

COPY Database.sql .

#RUN /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Password2023

#RUN /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Password2023 -i Database.sql